id: 1
cardNumber: 1
dexStats: "NO. 0001"
name: 'Samuele'
hitpoints: 110
typeId: 9
typeImageId: 9
subtypeId: 2
ability:
  name: 'Letâ€™s go to a party!'
  description: 'Don Samuele ha il talento raro di accendere l''allegria con una benedizione in tasca,
    pronta all''uso. Risultato: anche la sacrestia ogni tanto sembra una pista da ballo.'
  energycost:
    a:
      typeId: 3
    b:
      typeId: 7
    c:
      typeId: 4
    d:
      typeId: 10
attack:
  name: 'Turibolo Rotante'
  description: 'Un Incenso a Nebbia: atmosfera mistica, ma con vibe da festa patronale: sembra una cosa da
    manuale, ma don Samuele la fa con stile. Critico su chi prende la vita troppo sul serio.'
  damage: 10
resistanceTypeId: 2
resistanceAmount: 30
weaknessTypeId: 3
weaknessModifier: plus
weaknessAmount: 10
