id: 1
cardNumber: 1
dexStats: "NO. 0001"
name: 'Samuele'
hitpoints: 110
typeId: 9
typeImageId: 9
subtypeId: 2
ability:
  name: 'Let''s Go to a Party'
  description: 'Sempre pronto a festeggiare con amici e parenti, Samu accende l''allegria senza mai perdere il tono giusto. Se compare il prosecco, il sorriso diventa contagioso.'
  energycost:
    a:
      typeId: 3
    b:
      typeId: 7
    c:
      typeId: 4
    d:
      typeId: 10
attack:
  name: 'Turibolo Rotante'
  description: 'Con gesto preciso e sorprendentemente coreografico, don Samuele fa oscillare il turibolo con tale sicurezza che l''incenso avvolge tutti. Atmosfera solenne e facce estasiate garantite.'
  damage: 10
resistanceTypeId: 2
resistanceAmount: 30
weaknessTypeId: 3
weaknessModifier: plus
weaknessAmount: 10
