id: 2
cardNumber: 2
dexStats: "NO. 0002"
name: 'Samu'
hitpoints: 80
typeId: 8
typeImageId: 8
subtypeId: 2
ability:
  name: 'Voce da tenore (shhh)'
  description: 'Quando don Samuele entra in scena, l''atmosfera cambia: tira fuori la chitarra liturgica, 
    mette tutti in modalità Alleluia e sì, il sorriso diventa obbligatorio.'
  energycost:
    a:
      typeId: 2
    b:
      typeId: 10
    c:
      typeId: 1
    d:
      typeId: 9
attack:
  name: 'Benedizione a Sorpresa'
  description: 'Con il Sacro & Spritz: brindisi sobrio, sorriso pieno, gratitudine ovunque, don Samuele
    spiazza tutti. L''effetto è immediato: risate, pace e un leggero profumo d''incenso.'
  damage: 40
resistanceTypeId: 4
resistanceAmount: 10
weaknessTypeId: 8
weaknessModifier: plus
weaknessAmount: 30
