id: 2
cardNumber: 2
dexStats: "NO. 0002"
name: 'Samu'
hitpoints: 80
typeId: 8
typeImageId: 8
subtypeId: 2
ability:
  name: 'Voce da Tenore (ma non diciamoglielo)'
  description: 'Non perde occasione di cantare litanie, salmi e inni con entusiasmo travolgente. Se parte quello dell''Inter, l''intensità raddoppia.'
  energycost:
    a:
      typeId: 2
    b:
      typeId: 10
    c:
      typeId: 1
    d:
      typeId: 9
attack:
  name: 'Benedizione a Sorpresa'
  description: 'Quando meno te l''aspetti, arriva la benedizione: rapida, chiara, definitiva. Non sai bene come, ma ti senti già meglio. Amen.'
  damage: 40
resistanceTypeId: 4
resistanceAmount: 10
weaknessTypeId: 8
weaknessModifier: plus
weaknessAmount: 30
