id: 3
cardNumber: 3
dexStats: "NO. 0003"
name: 'Mega Samuele'
hitpoints: 60
typeId: 1
typeImageId: 1
subtypeId: 1
ability:
  name: 'Sorriso da Sacrestia'
  description: 'Quando don Samuele entra in scena, l''atmosfera cambia: firma con sorriso ogni incontro: la
    gente se ne va più leggera e sì, il sorriso diventa obbligatorio.'
  energycost:
    a:
      typeId: 1
    b:
      typeId: 10
    c:
      typeId: 7
    d:
      typeId: 4
attack:
  name: 'Incenso a Nebbia'
  description: 'Disperde i nemici nei pensieri del loro cuore con una nebbia che neanche in Val Padana. Fumogeno, spostati!'
  damage: 20
resistanceTypeId: 10
resistanceAmount: 10
weaknessTypeId: 9
weaknessModifier: plus
weaknessAmount: 30
