id: 3
cardNumber: 3
dexStats: "NO. 0003"
name: 'Mega Samuele'
hitpoints: 60
typeId: 1
typeImageId: 1
subtypeId: 1
ability:
  name: 'Sguardo Pastorale'
  description: 'Ti guarda, ti ascolta, capisce. Senza troppe parole rimette ordine nei pensieri e riporta la pace dove serve.'
  energycost:
    a:
      typeId: 1
    b:
      typeId: 10
    c:
      typeId: 7
    d:
      typeId: 4
attack:
  name: 'Omelia Mic Drop'
  description: 'Due minuti, una frase perfetta, silenzio totale. Parla, chiude, centro. L''effetto dura pi√π di un tormentone estivo.'
  damage: 20
resistanceTypeId: 10
resistanceAmount: 10
weaknessTypeId: 9
weaknessModifier: plus
weaknessAmount: 30
