id: 4
cardNumber: 4
dexStats: "NO. 0004"
name: 'Mega Samuele'
hitpoints: 30
typeId: 3
typeImageId: 3
subtypeId: 1
ability:
  name: 'Prosecco Benedetto'
  description: 'Attiva questa abilità e succede il bello: tira fuori la chitarra liturgica e mette tutti in
    modalità Alleluia. Effetto collaterale: clima di famiglia garantito.'
  energycost:
    a:
      typeId: 5
    b:
      typeId: 7
    c:
      typeId: 4
    d:
      typeId: 6
attack:
  name: 'Amen a Colpo Secco'
  description: 'Quando parte il Campanello Triplo che sveglia anche i distratti (con dolcezza), non c''''è
    difesa: ti ritrovi benedetto e con la faccia che ride.'
  damage: 30
resistanceTypeId: 4
resistanceAmount: 30
weaknessTypeId: 1
weaknessModifier: plus
weaknessAmount: 20
