id: 4
cardNumber: 4
dexStats: NO. 0004
name: SuperSamuele
hitpoints: 20
typeId: 6
typeImageId: 6
subtypeId: 1
ability:
  name: Manuale del Seminario in Tasca
  description: Tra libri e appunti, Samu trova sempre la pagina giusta al momento giusto. Ti permette
    di pescare la frase perfetta senza fare figure in latino (quasi sempre).
  energycost:
    a:
      typeId: 6
    b:
      typeId: 10
    c:
      typeId: 1
    d:
      typeId: 7
attack:
  name: Omelia-Lampo
  description: 'Tre frasi, un esempio da vita vera e un finale che spacca: danno emotivo alle
    distrazioni e bonus attenzione a tutti.'
  damage: 22
resistanceTypeId: 8
resistanceModifier: minus
resistanceAmount: 10
weaknessTypeId: 10
weaknessModifier: times
weaknessAmount: 32
