id: 4
cardNumber: 4
dexStats: "NO. 0004"
name: 'Mega Samuele'
hitpoints: 30
typeId: 3
typeImageId: 3
subtypeId: 1
ability:
  name: 'Zero Imbarazzo'
  description: 'Con una battuta elegante e un sorriso sincero, fa sentire tutti a casa: dal primo banco all''ultimo tavolo.'
  energycost:
    a:
      typeId: 5
    b:
      typeId: 7
    c:
      typeId: 4
    d:
      typeId: 6
attack:
  name: 'Pace a Catena'
  description: 'Parte da una stretta di mano e in pochi secondi tutta la chiesa sorride. L''energia positiva si propaga pi√π veloce di un coro allo stadio.'
  damage: 30
resistanceTypeId: 4
resistanceAmount: 30
weaknessTypeId: 1
weaknessModifier: plus
weaknessAmount: 20
