id: 5
cardNumber: 5
dexStats: "NO. 0005"
name: 'Super Samu'
hitpoints: 140
typeId: 5
typeImageId: 5
subtypeId: 3
ability:
  name: 'Energia da Oratorio'
  description: 'Tra celebrazione e festa, trova sempre la carica giusta. Sa essere solenne e subito dopo complice di una risata.'
  energycost:
    a:
      typeId: 7
    b:
      typeId: 1
    c:
      typeId: 9
    d:
      typeId: 5
attack:
  name: 'Processione con Passo Deciso'
  description: 'Cammina solenne ma con leggerezza. Non corre, non rallenta: guida. E tutti lo seguono senza nemmeno accorgersene.'
  damage: 30
resistanceTypeId: 5
resistanceAmount: 20
weaknessTypeId: 10
weaknessModifier: plus
weaknessAmount: 20
