id: 5
cardNumber: 5
dexStats: "NO. 0005"
name: 'Super Samu'
hitpoints: 140
typeId: 5
typeImageId: 5
subtypeId: 3
ability:
  name: 'Omèlia Sprint'
  description: 'don Samuele ha il talento raro di serve caffè in sacrestia come se fosse un rito: e funziona
    davvero. Risultato: anche la sacrestia sembra una pista da ballo (con rispetto).'
  energycost:
    a:
      typeId: 7
    b:
      typeId: 1
    c:
      typeId: 9
    d:
      typeId: 5
attack:
  name: 'Aspersione Splash'
  description: 'la Benedizione a Sorpresa: gesto fulmineo, cuore gigante, effetto ''Amen!'': sembra una cosa
    da manuale, ma don Samuele la fa con stile. Critico su chi prende la vita troppo sul serio.'
  damage: 30
resistanceTypeId: 5
resistanceAmount: 20
weaknessTypeId: 10
weaknessModifier: plus
weaknessAmount: 20
