id: 6
cardNumber: 6
dexStats: "NO. 0006"
name: 'Samu'
hitpoints: 130
typeId: 10
typeImageId: 10
subtypeId: 3
ability:
  name: 'Organizzazione Pastorale'
  description: 'Se qualcosa è fuori posto, Samu lo sistema con calma e precisione. Ordine esterno, serenità interna.'
  energycost:
    a:
      typeId: 10
    b:
      typeId: 1
    c:
      typeId: 6
    d:
      typeId: 7
attack:
  name: 'Gloria a Volume Liturgico'
  description: 'Intona il Gloria con entusiasmo controllato: non è un concerto, ma quasi. L''assemblea si alza di un tono e di umore.'
  damage: 20
resistanceTypeId: 5
resistanceAmount: 30
weaknessTypeId: 9
weaknessModifier: times
weaknessAmount: 2
