id: 7
cardNumber: 7
dexStats: "NO. 0007"
name: 'Super Samuele'
hitpoints: 20
typeId: 9
typeImageId: 9
subtypeId: 1
ability:
  name: 'Pazienza Infinita'
  description: 'Anche davanti a domande ripetute o situazioni complicate, mantiene calma e gentilezza. Nessuno si sente fuori posto.'
  energycost:
    a:
      typeId: 7
    b:
      typeId: 2
    c:
      typeId: 6
    d:
      typeId: 1
attack:
  name: 'Confessionale Reset'
  description: 'Ascolta con equilibrio e risponde con misura. Quando esci, sembra che qualcuno abbia aggiornato il sistema operativo dell''anima.'
  damage: 10
resistanceTypeId: 2
resistanceAmount: 10
weaknessTypeId: 1
weaknessModifier: plus
weaknessAmount: 10
