id: 7
cardNumber: 7
dexStats: "NO. 0007"
name: 'Super Samuele'
hitpoints: 20
typeId: 9
typeImageId: 9
subtypeId: 1
ability:
  name: 'Rosario Remix'
  description: 'Attiva questa abilità e succede il bello: tiene il gruppo unito: nessuno resta indietro,
    nessuno resta solo. Effetto collaterale: clima di famiglia garantito.'
  energycost:
    a:
      typeId: 7
    b:
      typeId: 2
    c:
      typeId: 6
    d:
      typeId: 1
attack:
  name: 'Pace Scambiata Rapida'
  description: 'Quando parte il Campanello Triplo che sveglia anche i distratti (con dolcezza), non c''''è
    difesa: ti ritrovi benedetto e con la faccia che ride.'
  damage: 10
resistanceTypeId: 2
resistanceAmount: 10
weaknessTypeId: 1
weaknessModifier: plus
weaknessAmount: 10
