id: 8
cardNumber: 8
dexStats: "NO. 0008"
name: 'Super Samuele'
hitpoints: 120
typeId: 7
typeImageId: 7
subtypeId: 2
ability:
  name: 'Pace & Love (e Amen)'
  description: 'don Samuele ha il talento raro di canta litanie e inni come un tenoreâ€¦ soprattutto quando
    parte quello dell''''Inter. Risultato: anche la sacrestia sembra una pista da ballo (con
    rispetto).'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 2
    c:
      typeId: 6
    d:
      typeId: 7
attack:
  name: 'Coro a Squarciagola'
  description: 'le Campane in Dubstep: vibrazione pura, nessuno resta fermo: sembra una cosa da manuale, ma
    don Samuele la fa con stile. Critico su chi prende la vita troppo sul serio.'
  damage: 20
resistanceTypeId: 5
resistanceAmount: 20
weaknessTypeId: 10
weaknessModifier: plus
weaknessAmount: 30
