id: 8
cardNumber: 8
dexStats: "NO. 0008"
name: 'Super Samuele'
hitpoints: 120
typeId: 7
typeImageId: 7
subtypeId: 2
ability:
  name: 'Presenza Costante'
  description: 'Quando qualcuno ha bisogno, lui c''è. Senza effetti speciali, ma con una fedeltà che rassicura.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 2
    c:
      typeId: 6
    d:
      typeId: 7
attack:
  name: 'Alleluia Energizzante'
  description: 'Parte l''Alleluia e l''atmosfera cambia: non è rumore, è entusiasmo. Anche chi era distratto torna presente.'
  damage: 20
resistanceTypeId: 5
resistanceAmount: 20
weaknessTypeId: 10
weaknessModifier: plus
weaknessAmount: 30
