id: 9
cardNumber: 9
dexStats: "NO. 0009"
name: 'Mega Samuele'
hitpoints: 30
typeId: 5
typeImageId: 5
subtypeId: 1
ability:
  name: 'Umiltà Disarmante'
  description: 'Anche quando è al centro dell''attenzione, resta semplice. L''ego non sale mai sull''altare.'
  energycost:
    a:
      typeId: 3
    b:
      typeId: 8
    c:
      typeId: 1
    d:
      typeId: 5
attack:
  name: 'Vangelo Uppercut'
  description: 'Legge poche righe e colpisce dritto al cuore. Non fa male: fa bene. Ma l''impatto si sente.'
  damage: 10
resistanceTypeId: 9
resistanceAmount: 30
weaknessTypeId: 4
weaknessModifier: times
weaknessAmount: 2
