id: 10
cardNumber: 10
dexStats: "NO. 0010"
name: 'Super Samu'
hitpoints: 90
typeId: 5
typeImageId: 5
subtypeId: 2
ability:
  name: 'Gioia Contagiosa'
  description: 'Il suo sorriso è una firma: rende leggera la solennità e profonda la festa. Con lui la fede non perde mai il buonumore.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 4
    c:
      typeId: 3
    d:
      typeId: 1
attack:
  name: 'Alleluia a Volume 3x'
  name: 'Uscita Solenne con High-Five'
  description: 'Saluta tutti all''uscita, uno per uno. Benedice, scherza e lascia una scia di nostalgia felice.'
  damage: 40
resistanceTypeId: 4
resistanceAmount: 30
weaknessTypeId: 8
weaknessModifier: times
weaknessAmount: 2
