id: 11
cardNumber: 11
dexStats: NO. 0011
name: Samu
hitpoints: 70
typeId: 3
typeImageId: 3
subtypeId: 3
ability:
  name: WhatsApp del Buon Pastore
  description: 'Risponde con un audio breve ma efficacissimo: «Ci sono». Ti salva la serata e
    spesso anche la settimana.'
  energycost:
    a:
      typeId: 6
    b:
      typeId: 1
    c:
      typeId: 4
    d:
      typeId: 5
attack:
  name: Cero “Accendi-Allegria”
  description: 'Accende il cero e, insieme, accende la stanza: sembra una luce da festa. L’avversario
    resta abbagliato dalla gioia.'
  damage: 45
resistanceTypeId: 8
resistanceModifier: minus
resistanceAmount: 4
weaknessTypeId: 1
weaknessModifier: minus
weaknessAmount: 24
