id: 11
cardNumber: 11
dexStats: "NO. 0011"
name: 'Super Samu'
hitpoints: 60
typeId: 1
typeImageId: 1
subtypeId: 1
ability:
  name: 'Coro da Curva'
  description: 'Attiva questa abilità e succede il bello: canta litanie e inni come un tenore… soprattutto
    quando parte quello dell''''Inter. Effetto collaterale: clima di famiglia garantito.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 2
    c:
      typeId: 3
    d:
      typeId: 7
attack:
  name: 'Genuflessione Ninja'
  description: 'Quando parte le Campane in Dubstep: vibrazione pura, nessuno resta fermo, non c''''è difesa:
    ti ritrovi benedetto e con la faccia che ride.'
  damage: 20
resistanceTypeId: 2
resistanceAmount: 30
weaknessTypeId: 5
weaknessModifier: plus
weaknessAmount: 30
