id: 11
cardNumber: 11
dexStats: "NO. 0011"
name: 'Super Samu'
hitpoints: 60
typeId: 1
typeImageId: 1
subtypeId: 1
ability:
  name: 'Carisma da Altare'
  description: 'Quando sale all''altare, cambia l''aria. Non per teatralità, ma per presenza: ti accorgi che sta succedendo qualcosa di importante.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 2
    c:
      typeId: 3
    d:
      typeId: 7
attack:
  name: 'Incenso Strategico'
  description: 'Una rotazione perfetta del turibolo e l''atmosfera si trasforma. Solennità in aumento, distrazioni in fuga.'
  damage: 20
resistanceTypeId: 2
resistanceAmount: 30
weaknessTypeId: 5
weaknessModifier: plus
weaknessAmount: 30
