id: 12
cardNumber: 12
dexStats: "NO. 0012"
name: 'Super Samuele'
hitpoints: 150
typeId: 4
typeImageId: 4
subtypeId: 3
ability:
  name: 'Battuta Pastorale'
  description: 'Sa inserire la frase giusta al momento giusto: alleggerisce senza banalizzare e fa sorridere senza sminuire.'
  energycost:
    a:
      typeId: 10
    b:
      typeId: 3
    c:
      typeId: 7
    d:
      typeId: 9
attack:
  name: 'Orazione Lampo'
  description: 'Preghiera breve, mirata, precisa. Colpisce il cuore e lascia un effetto che dura ben oltre l''Amen.'
  damage: 50
resistanceTypeId: 5
resistanceAmount: 30
weaknessTypeId: 4
weaknessModifier: plus
weaknessAmount: 30
