id: 12
cardNumber: 12
dexStats: "NO. 0012"
name: 'Super Samuele'
hitpoints: 150
typeId: 4
typeImageId: 4
subtypeId: 3
ability:
  name: 'Bolle di Gioia'
  description: 'Quando don Samuele entra in scena, l''''atmosfera cambia: accende l''''allegria anche con una
    benedizione in tasca, pronta all''''uso E sì, il sorriso diventa obbligatorio.'
  energycost:
    a:
      typeId: 10
    b:
      typeId: 3
    c:
      typeId: 7
    d:
      typeId: 9
attack:
  name: 'Segno della Croce Perfetto'
  description: 'Quando parte il Rosario a Tempo: un passo, un''Ave, e via con il cuore leggero, non c''''è
    difesa: ti ritrovi benedetto e con la faccia che ride.'
  damage: 50
resistanceTypeId: 5
resistanceAmount: 30
weaknessTypeId: 4
weaknessModifier: plus
weaknessAmount: 30
