id: 13
cardNumber: 13
dexStats: "NO. 0013"
name: 'Super Samu'
hitpoints: 60
typeId: 1
typeImageId: 1
subtypeId: 1
ability:
  name: 'Ascolto Attivo'
  description: 'Quando qualcuno parla, lui ascolta davvero. Non interrompe, non giudica: crea spazio e fiducia.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 9
    c:
      typeId: 6
    d:
      typeId: 5
attack:
  name: 'Silenzio Potente'
  description: 'Un momento di silenzio guidato da lui vale pi√π di mille parole. L''avversario perde il rumore interiore.'
  damage: 50
resistanceTypeId: 5
resistanceAmount: 30
weaknessTypeId: 3
weaknessModifier: times
weaknessAmount: 2
