id: 13
cardNumber: 13
dexStats: "NO. 0013"
name: 'Super Samu'
hitpoints: 60
typeId: 1
typeImageId: 1
subtypeId: 1
ability:
  name: 'Chitarra Liturgica'
  description: 'Quando don Samuele entra in scena, l''''atmosfera cambia: firma con sorriso ogni incontro: la
    gente se ne va più leggera E sì, il sorriso diventa obbligatorio.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 9
    c:
      typeId: 6
    d:
      typeId: 5
attack:
  name: 'OmèlIa Drop'
  description: 'la Genuflessione Ninja: silenziosa, precisa, e ti fa venir voglia di fare meglio: sembra una
    cosa da manuale, ma don Samuele la fa con stile. Critico su chi prende la vita troppo sul
    serio.'
  damage: 50
resistanceTypeId: 5
resistanceAmount: 30
weaknessTypeId: 3
weaknessModifier: times
weaknessAmount: 2
