id: 13
cardNumber: 13
dexStats: NO. 0013
name: SuperSamu
hitpoints: 110
typeId: 10
typeImageId: 10
subtypeId: 3
ability:
  name: Lettore da Palco
  description: 'Proclama con chiarezza e un pizzico di teatro: anche chi era in fondo capisce
    tutto. Aumenta la “precisione” delle tue mosse.'
  energycost:
    a:
      typeId: 3
    b:
      typeId: 9
    c:
      typeId: 5
    d:
      typeId: 6
attack:
  name: Chierichetto Turbo
  description: 'Movimenti rapidi: messale, ampolline, campanello… tutto in sequenza. L’avversario
    non capisce più da dove arriva il danno.'
  damage: 37
resistanceTypeId: 5
resistanceModifier: plus
resistanceAmount: 19
weaknessTypeId: 5
weaknessModifier: times
weaknessAmount: 14
