id: 14
cardNumber: 14
dexStats: "NO. 0014"
name: 'Samuele'
hitpoints: 50
typeId: 1
typeImageId: 1
subtypeId: 1
ability:
  name: 'Stile Liturgico Naturale'
  description: 'Ogni gesto è curato ma mai rigido. La solennità diventa accessibile e la formalità si trasforma in eleganza.'
  energycost:
    a:
      typeId: 6
    b:
      typeId: 4
    c:
      typeId: 3
    d:
      typeId: 5
attack:
  name: 'Segno della Croce Preciso'
  description: 'Traccia il segno con calma e convinzione. Semplice, ma talmente centrato che lascia il segno.'
  damage: 10
resistanceTypeId: 6
resistanceAmount: 30
weaknessTypeId: 3
weaknessModifier: times
weaknessAmount: 2
