id: 14
cardNumber: 14
dexStats: "NO. 0014"
name: 'Samuele'
hitpoints: 50
typeId: 1
typeImageId: 1
subtypeId: 1
ability:
  name: 'Parabola da Bar'
  description: 'È la sua mossa segreta: fa ''calma olimpica'': anche se succede di tutto, lui resta centrato.
    Chi lo incontra capisce subito che la gioia può essere… liturgica.'
  energycost:
    a:
      typeId: 6
    b:
      typeId: 4
    c:
      typeId: 3
    d:
      typeId: 5
attack:
  name: 'Campanello Triplo'
  description: 'Quando parte la Benedizione a Sorpresa: gesto fulmineo, cuore gigante, effetto ''Amen!'', non
    c''''è difesa: ti ritrovi benedetto e con la faccia che ride.'
  damage: 10
resistanceTypeId: 6
resistanceAmount: 30
weaknessTypeId: 3
weaknessModifier: times
weaknessAmount: 2
