id: 15
cardNumber: 15
dexStats: "NO. 0015"
name: 'Mega Samuele'
hitpoints: 60
typeId: 3
typeImageId: 3
subtypeId: 1
ability:
  name: 'Kyrie Karaoke'
  description: 'Quando don Samuele entra in scena, l''''atmosfera cambia: usa l''''ironia con delicatezza: fa
    ridere senza ferire, mai E sì, il sorriso diventa obbligatorio.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 3
    c:
      typeId: 9
    d:
      typeId: 5
attack:
  name: 'Vangelo a Effetto'
  description: 'Quando parte un ''Alleluia'' a volume 11: non è rumore, è gioia che trabocca, non c''''è difesa:
    ti ritrovi benedetto e con la faccia che ride.'
  damage: 10
resistanceTypeId: 1
resistanceAmount: 30
weaknessTypeId: 4
weaknessModifier: times
weaknessAmount: 2
