id: 15
cardNumber: 15
dexStats: "NO. 0015"
name: 'Mega Samuele'
hitpoints: 60
typeId: 3
typeImageId: 3
subtypeId: 1
ability:
  name: 'Empatia Immediata'
  description: 'In pochi secondi capisce chi ha davanti. Adatta tono, parole e sorriso senza perdere autenticit√†.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 3
    c:
      typeId: 9
    d:
      typeId: 5
attack:
  name: 'Parola Che Raggiunge'
  description: 'Una frase ben costruita, detta con convinzione. Non alza la voce, ma arriva lontano.'
  damage: 10
resistanceTypeId: 1
resistanceAmount: 30
weaknessTypeId: 4
weaknessModifier: times
weaknessAmount: 2
