id: 16
cardNumber: 16
dexStats: "NO. 0016"
name: 'Super Samuele'
hitpoints: 50
typeId: 1
typeImageId: 1
subtypeId: 1
ability:
  name: 'Serenità Incrollabile'
  description: 'Anche quando qualcosa va storto, resta saldo. La calma è contagiosa e il caos perde forza.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 7
    c:
      typeId: 4
    d:
      typeId: 1
attack:
  name: 'Ritmo della Celebrazione'
  description: 'Guida la celebrazione con tempi perfetti. Nessuna fretta, nessuna lentezza: equilibrio che spiazza ogni distrazione.'
  damage: 30
resistanceTypeId: 5
resistanceAmount: 30
weaknessTypeId: 7
weaknessModifier: times
weaknessAmount: 2
