id: 17
cardNumber: 17
dexStats: "NO. 0017"
name: 'Super Samu'
hitpoints: 30
typeId: 3
typeImageId: 3
subtypeId: 1
ability:
  name: 'Accoglienza Autentica'
  description: 'Ti saluta guardandoti negli occhi. Non è formalità: è presenza vera che fa sentire riconosciuti.'
  energycost:
    a:
      typeId: 9
    b:
      typeId: 8
    c:
      typeId: 2
    d:
      typeId: 10
attack:
  name: 'Pace Mirata'
  description: 'Una stretta di mano ben data e il clima cambia. L''ostilità si scioglie senza nemmeno accorgersene.'
  damage: 20
resistanceTypeId: 6
resistanceAmount: 10
weaknessTypeId: 10
weaknessModifier: times
weaknessAmount: 2
