id: 17
cardNumber: 17
dexStats: "NO. 0017"
name: 'Super Samu'
hitpoints: 30
typeId: 3
typeImageId: 3
subtypeId: 1
ability:
  name: 'Miracolo del Parcheggio'
  description: 'È la sua mossa segreta: si muove tra altare e vita quotidiana con naturalezza da
    fuoriclasse. Chi lo incontra capisce subito che la gioia può essere… liturgica.'
  energycost:
    a:
      typeId: 9
    b:
      typeId: 8
    c:
      typeId: 2
    d:
      typeId: 10
attack:
  name: 'Chiusura ''Andate in Pace'''
  description: 'la Genuflessione Ninja: silenziosa, precisa, e ti fa venir voglia di fare meglio: sembra una
    cosa da manuale, ma don Samuele la fa con stile. Critico su chi prende la vita troppo sul
    serio.'
  damage: 20
resistanceTypeId: 6
resistanceAmount: 10
weaknessTypeId: 10
weaknessModifier: times
weaknessAmount: 2
