id: 18
cardNumber: 18
dexStats: "NO. 0018"
name: 'Mega Samu'
hitpoints: 170
typeId: 8
typeImageId: 8
subtypeId: 3
ability:
  name: 'Fede con Sorriso'
  description: 'Riesce a parlare di cose profonde senza perdere leggerezza. Serio nei contenuti, luminoso nel tono.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 5
    c:
      typeId: 9
    d:
      typeId: 6
attack:
  name: 'Alleluia Crescendo'
  description: 'Parte piano e cresce con entusiasmo. L''assemblea si alza insieme, come guidata da un''onda positiva.'
  damage: 40
resistanceTypeId: 5
resistanceAmount: 20
weaknessTypeId: 7
weaknessModifier: times
weaknessAmount: 2
