id: 18
cardNumber: 18
dexStats: "NO. 0018"
name: 'Mega Samu'
hitpoints: 170
typeId: 8
typeImageId: 8
subtypeId: 3
ability:
  name: 'Acqua Santa Splash'
  description: 'È la sua mossa segreta: serve caffè in sacrestia come se fosse un rito: e funziona davvero.
    Chi lo incontra capisce subito che la gioia può essere… liturgica.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 5
    c:
      typeId: 9
    d:
      typeId: 6
attack:
  name: 'Sguardo Pastorale Critico'
  description: 'Quando parte la Stretta di Mano Apostolica: ti tira su senza fare rumore, non c''''è difesa:
    ti ritrovi benedetto e con la faccia che ride.'
  damage: 40
resistanceTypeId: 5
resistanceAmount: 20
weaknessTypeId: 7
weaknessModifier: times
weaknessAmount: 2
