id: 19
cardNumber: 19
dexStats: NO. 0019
name: SuperSamuele
hitpoints: 70
typeId: 10
typeImageId: 10
subtypeId: 3
ability:
  name: Sorriso “Amen”
  description: Dici “Amen” e sembra che il mondo sia un po’ più leggero. Una volta per turno puoi
    neutralizzare un effetto “muso lungo”.
  energycost:
    a:
      typeId: 1
    b:
      typeId: 9
    c:
      typeId: 5
    d:
      typeId: 3
attack:
  name: Diaconia Schiacciata
  description: 'Servizio totale: arriva, sistema, risolve, e ti guarda come per dire «tranquillo».
    L’avversario subisce danno da efficienza.'
  damage: 34
resistanceTypeId: 10
resistanceModifier: times
resistanceAmount: 15
weaknessTypeId: 8
weaknessModifier: plus
weaknessAmount: 32
