id: 19
cardNumber: 19
dexStats: "NO. 0019"
name: 'Mega Samu'
hitpoints: 40
typeId: 8
typeImageId: 8
subtypeId: 1
ability:
  name: 'Abbraccio Pastorale'
  description: 'don Samuele ha il talento raro di mescola Bibbia e playlist: la Parola resta… e anche il
    ritornello. Risultato: anche la sacrestia sembra una pista da ballo (con rispetto).'
  energycost:
    a:
      typeId: 7
    b:
      typeId: 5
    c:
      typeId: 3
    d:
      typeId: 10
attack:
  name: 'Confessionale KO (di tenerezza)'
  description: 'Con la Stretta di Mano Apostolica: ti tira su senza fare rumore, don Samuele spiazza tutti.
    L''''effetto è immediato: risate, pace e un leggero profumo d''''incenso.'
  damage: 40
resistanceTypeId: 6
resistanceAmount: 30
weaknessTypeId: 5
weaknessModifier: plus
weaknessAmount: 20
