id: 19
cardNumber: 19
dexStats: "NO. 0019"
name: 'Mega Samu'
hitpoints: 40
typeId: 8
typeImageId: 8
subtypeId: 1
ability:
  name: 'Presenza Instancabile'
  description: 'Dopo la Messa è ancora lì: saluta, ascolta, scherza. L''energia sembra non finire mai.'
  energycost:
    a:
      typeId: 7
    b:
      typeId: 5
    c:
      typeId: 3
    d:
      typeId: 10
attack:
  name: 'Saluto Finale Devastante'
  description: 'All''uscita distribuisce sorrisi e parole buone. L''avversario viene colpito da nostalgia felice.'
  damage: 40
resistanceTypeId: 6
resistanceAmount: 30
weaknessTypeId: 5
weaknessModifier: plus
weaknessAmount: 20
