id: 20
cardNumber: 20
dexStats: "NO. 0020"
name: 'Mega Samu'
hitpoints: 50
typeId: 2
typeImageId: 2
subtypeId: 1
ability:
  name: 'Coerenza Silenziosa'
  description: 'Non serve spiegare tutto: il modo in cui vive parla per lui. E questo vale pi√π di qualsiasi discorso.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 6
    c:
      typeId: 1
    d:
      typeId: 9
attack:
  name: 'Amen Definitivo'
  description: 'Pronuncia l''Amen con tale convinzione che chiude ogni dubbio. Fine del turno, inizio della pace.'  
  damage: 20
resistanceTypeId: 2
resistanceAmount: 20
weaknessTypeId: 10
weaknessModifier: plus
weaknessAmount: 10
