id: 20
cardNumber: 20
dexStats: "NO. 0020"
name: 'Mega Samu'
hitpoints: 50
typeId: 2
typeImageId: 2
subtypeId: 1
ability:
  name: 'Agenda da Prete Giovane'
  description: 'Attiva questa abilit√† e succede il bello: accende l''''allegria anche con una benedizione in
    tasca, pronta all''''uso. Effetto collaterale: clima di famiglia garantito.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 6
    c:
      typeId: 1
    d:
      typeId: 9
attack:
  name: 'Acqua Santa Critical Hit'
  description: 'la Benedizione a Sorpresa: gesto fulmineo, cuore gigante, effetto ''Amen!'': sembra una cosa
    da manuale, ma don Samuele la fa con stile. Critico su chi prende la vita troppo sul serio.'
  damage: 20
resistanceTypeId: 2
resistanceAmount: 20
weaknessTypeId: 10
weaknessModifier: plus
weaknessAmount: 10
