id: 21
cardNumber: 21
dexStats: "NO. 0021"
name: 'Mega Samu'
hitpoints: 30
typeId: 5
typeImageId: 5
subtypeId: 1
ability:
  name: 'Autorit√† Gentile'
  description: 'Non alza la voce, non impone. Basta uno sguardo sereno e una parola ben scelta per ristabilire ordine e armonia.'
  energycost:
    a:
      typeId: 4
    b:
      typeId: 1
    c:
      typeId: 9
    d:
      typeId: 6
attack:
  name: 'Omelia a Fuoco Lento'
  description: 'Parte tranquillo, costruisce con calma, e alla fine centra il punto con precisione chirurgica. Colpo profondo, senza rumore.'
  damage: 50
resistanceTypeId: 7
resistanceAmount: 30
weaknessTypeId: 3
weaknessModifier: plus
weaknessAmount: 20
