id: 21
cardNumber: 21
dexStats: "NO. 0021"
name: 'Mega Samu'
hitpoints: 30
typeId: 5
typeImageId: 5
subtypeId: 1
ability:
  name: 'Messaggio Vocale Celeste'
  description: 'È la sua mossa segreta: serve caffè in sacrestia come se fosse un rito: e funziona davvero.
    Chi lo incontra capisce subito che la gioia può essere… liturgica.'
  energycost:
    a:
      typeId: 4
    b:
      typeId: 1
    c:
      typeId: 9
    d:
      typeId: 6
attack:
  name: 'Parrocchia Shuffle'
  description: 'la Benedizione a Sorpresa: gesto fulmineo, cuore gigante, effetto ''Amen!'': sembra una cosa
    da manuale, ma don Samuele la fa con stile. Critico su chi prende la vita troppo sul serio.'
  damage: 50
resistanceTypeId: 7
resistanceAmount: 30
weaknessTypeId: 3
weaknessModifier: plus
weaknessAmount: 20
