id: 22
cardNumber: 22
dexStats: NO. 0022
name: Samu
hitpoints: 60
typeId: 3
typeImageId: 3
subtypeId: 2
ability:
  name: Zero Panico, Solo Pace
  description: Quando tutti agitati, lui alza una mano e la stanza cambia aria. Riduce drasticamente
    il caos.
  energycost:
    a:
      typeId: 10
    b:
      typeId: 4
    c:
      typeId: 8
    d:
      typeId: 7
attack:
  name: Benedizione “Multitarget”
  description: 'Una benedizione per te, una per lui, una per chi guarda: nessuno si salva dall’Amen.
    Danno distribuito e sorriso garantito.'
  damage: 31
resistanceTypeId: 3
resistanceModifier: times
resistanceAmount: 28
weaknessTypeId: 2
weaknessModifier: times
weaknessAmount: 21
