id: 22
cardNumber: 22
dexStats: "NO. 0022"
name: 'Samuele'
hitpoints: 30
typeId: 7
typeImageId: 7
subtypeId: 1
ability:
  name: 'Memoria dei Volti'
  description: 'Ricorda nomi, storie, dettagli. Ti sorprende con un “come stai?” che dimostra attenzione vera.'
  energycost:
    a:
      typeId: 2
    b:
      typeId: 6
    c:
      typeId: 9
    d:
      typeId: 5
attack:
  name: 'Salmo Coinvolgente'
  description: 'Intona il salmo con ritmo naturale e trascina tutti dentro. Anche i più timidi finiscono per rispondere.'
  damage: 30
resistanceTypeId: 7
resistanceAmount: 20
weaknessTypeId: 10
weaknessModifier: plus
weaknessAmount: 10
