id: 22
cardNumber: 22
dexStats: "NO. 0022"
name: 'Samuele'
hitpoints: 30
typeId: 7
typeImageId: 7
subtypeId: 1
ability:
  name: 'Niente Panico, è Provvidenza'
  description: 'Attiva questa abilità e succede il bello: ha lo ''stola style'': elegante, semplice, sempre a
    suo agio. Effetto collaterale: clima di famiglia garantito.'
  energycost:
    a:
      typeId: 2
    b:
      typeId: 6
    c:
      typeId: 9
    d:
      typeId: 5
attack:
  name: 'Oratorio Power-Up'
  description: 'don Samuele esegue il Sacro & Spritz: brindisi sobrio, sorriso pieno, gratitudine ovunque:
    colpo preciso, zero cattiveria, solo una valanga di ''Amen!'' e buonumore.'
  damage: 30
resistanceTypeId: 7
resistanceAmount: 20
weaknessTypeId: 10
weaknessModifier: plus
weaknessAmount: 10
