id: 23
cardNumber: 23
dexStats: "NO. 0023"
name: 'Super Samuele'
hitpoints: 40
typeId: 9
typeImageId: 9
subtypeId: 1
ability:
  name: 'Bontà a Doppio Turno'
  description: 'È la sua mossa segreta: tira fuori la chitarra liturgica e mette tutti in modalità Alleluia.
    Chi lo incontra capisce subito che la gioia può essere… liturgica.'
  energycost:
    a:
      typeId: 6
    b:
      typeId: 5
    c:
      typeId: 8
    d:
      typeId: 3
attack:
  name: 'Miracolo del ''Tutto a Posto'''
  description: 'il Campanello Triplo che sveglia anche i distratti (con dolcezza): sembra una cosa da
    manuale, ma don Samuele la fa con stile. Critico su chi prende la vita troppo sul serio.'
  damage: 10
resistanceTypeId: 5
resistanceAmount: 20
weaknessTypeId: 2
weaknessModifier: times
weaknessAmount: 2
