id: 23
cardNumber: 23
dexStats: "NO. 0023"
name: 'Super Samuele'
hitpoints: 40
typeId: 9
typeImageId: 9
subtypeId: 1
ability:
  name: 'Ironia Consacrata'
  description: 'Sa scherzare senza mai oltrepassare il limite. La battuta arriva, fa sorridere, e lascia intatta la dignit√† del momento.'
  energycost:
    a:
      typeId: 6
    b:
      typeId: 5
    c:
      typeId: 8
    d:
      typeId: 3
attack:
  name: 'Sorriso Disarmante'
  description: 'Un sorriso autentico che scioglie tensioni e mette tutti a proprio agio. Difese abbassate, clima ristabilito.'
  damage: 10
resistanceTypeId: 5
resistanceAmount: 20
weaknessTypeId: 2
weaknessModifier: times
weaknessAmount: 2
