id: 24
cardNumber: 24
dexStats: "NO. 0024"
name: 'Super Samu'
hitpoints: 40
typeId: 5
typeImageId: 5
subtypeId: 1
ability:
  name: 'Samu Social (con misura)'
  description: 'Quando don Samuele entra in scena, l''''atmosfera cambia: ha lo ''stola style'': elegante,
    semplice, sempre a suo agio E s√¨, il sorriso diventa obbligatorio.'
  energycost:
    a:
      typeId: 6
    b:
      typeId: 2
    c:
      typeId: 9
    d:
      typeId: 7
attack:
  name: 'Ritmo di Processione'
  description: 'don Samuele esegue un Amen Mic Drop: chiusura netta, applauso interiore assicurato: colpo
    preciso, zero cattiveria, solo una valanga di ''Amen!'' e buonumore.'
  damage: 20
resistanceTypeId: 5
resistanceAmount: 30
weaknessTypeId: 8
weaknessModifier: plus
weaknessAmount: 30
