id: 24
cardNumber: 24
dexStats: "NO. 0024"
name: 'Super Samu'
hitpoints: 40
typeId: 5
typeImageId: 5
subtypeId: 1
ability:
  name: 'Equilibrio Pastorale'
  description: 'Sa quando essere solenne e quando essere leggero. Alterna profondità e semplicità con naturalezza sorprendente.'
  energycost:
    a:
      typeId: 6
    b:
      typeId: 2
    c:
      typeId: 9
    d:
      typeId: 7
attack:
  name: 'Parola Calibrata'
  description: 'Sceglie i termini con cura e colpisce esattamente dove serve. Nessun eccesso, solo precisione.'
  damage: 20
resistanceTypeId: 5
resistanceAmount: 30
weaknessTypeId: 8
weaknessModifier: plus
weaknessAmount: 30
