id: 25
cardNumber: 25
dexStats: "NO. 0025"
name: 'Mega Samuele'
hitpoints: 170
typeId: 7
typeImageId: 7
subtypeId: 3
ability:
  name: 'Energia Silenziosa'
  description: 'Non Ã¨ rumoroso, ma la sua presenza si sente. Trasmette forza tranquilla che sostiene senza invadere.'
  energycost:
    a:
      typeId: 7
    b:
      typeId: 2
    c:
      typeId: 10
    d:
      typeId: 9
attack:
  name: 'Gesto Solenne'
  description: 'Un movimento lento, controllato, carico di significato. L''impatto emotivo supera qualsiasi effetto speciale.'
  damage: 10
resistanceTypeId: 4
resistanceAmount: 30
weaknessTypeId: 8
weaknessModifier: plus
weaknessAmount: 30
