id: 25
cardNumber: 25
dexStats: "NO. 0025"
name: 'Mega Samuele'
hitpoints: 170
typeId: 7
typeImageId: 7
subtypeId: 3
ability:
  name: 'Gioco di Sguardi'
  description: 'don Samuele ha il talento raro di accende la festa senza perdere il tono giusto, anche se
    spunta un prosecco. Risultato: anche la sacrestia sembra una pista da ballo (con rispetto).'
  energycost:
    a:
      typeId: 7
    b:
      typeId: 2
    c:
      typeId: 10
    d:
      typeId: 9
attack:
  name: 'Canto del Derby'
  description: 'Quando parte le Campane in Dubstep: vibrazione pura, nessuno resta fermo, non c''''Ã¨ difesa:
    ti ritrovi benedetto e con la faccia che ride.'
  damage: 10
resistanceTypeId: 4
resistanceAmount: 30
weaknessTypeId: 8
weaknessModifier: plus
weaknessAmount: 30
