id: 26
cardNumber: 26
dexStats: "NO. 0026"
name: 'Mega Samuele'
hitpoints: 80
typeId: 2
typeImageId: 2
subtypeId: 2
ability:
  name: 'Sermone in 60 secondi'
  description: 'don Samuele ha il talento raro di firma con sorriso ogni incontro: la gente se ne va pi√π
    leggera. Risultato: anche la sacrestia sembra una pista da ballo (con rispetto).'
  energycost:
    a:
      typeId: 2
    b:
      typeId: 1
    c:
      typeId: 5
    d:
      typeId: 10
attack:
  name: 'Grazia che Spiazza'
  description: 'un''''aspersione Splash che ti rinfresca l''''anima come una doccia d''''estate: sembra una cosa
    da manuale, ma don Samuele la fa con stile. Critico su chi prende la vita troppo sul serio.'
  damage: 40
resistanceTypeId: 5
resistanceAmount: 10
weaknessTypeId: 10
weaknessModifier: plus
weaknessAmount: 10
