id: 26
cardNumber: 26
dexStats: "NO. 0026"
name: 'Mega Samuele'
hitpoints: 80
typeId: 2
typeImageId: 2
subtypeId: 2
ability:
  name: 'Complicità Generazionale'
  description: 'Sa parlare ai giovani senza imitare, agli adulti senza distanziare. Ponte naturale tra mondi diversi.'
  energycost:
    a:
      typeId: 2
    b:
      typeId: 1
    c:
      typeId: 5
    d:
      typeId: 10
attack:
  name: 'Canto Guidato'
  description: 'Inizia lui, segue l''assemblea. L''intonazione è sicura e l''energia cresce battuta dopo battuta.'
  damage: 40
resistanceTypeId: 5
resistanceAmount: 10
weaknessTypeId: 10
weaknessModifier: plus
weaknessAmount: 10
