id: 27
cardNumber: 27
dexStats: "NO. 0027"
name: 'Mega Samuele'
hitpoints: 40
typeId: 4
typeImageId: 4
subtypeId: 1
ability:
  name: 'Calma Operativa'
  description: 'Anche quando c''è imprevisto, non si scompone. Sistema tutto con lucidità e un mezzo sorriso.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 9
    c:
      typeId: 4
    d:
      typeId: 2
attack:
  name: 'Rito Impeccabile'
  description: 'Sequenza perfetta di gesti e parole. Nessuna sbavatura, solo fluidità che lascia ammirati.'
  damage: 10
resistanceTypeId: 10
resistanceAmount: 10
weaknessTypeId: 3
weaknessModifier: times
weaknessAmount: 2
