id: 27
cardNumber: 27
dexStats: "NO. 0027"
name: 'Mega Samuele'
hitpoints: 40
typeId: 4
typeImageId: 4
subtypeId: 1
ability:
  name: 'Biscotto Oratoriano'
  description: 'don Samuele ha il talento raro di mescola Bibbia e playlist: la Parola restaâ€¦ e anche il
    ritornello. Risultato: anche la sacrestia sembra una pista da ballo (con rispetto).'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 9
    c:
      typeId: 4
    d:
      typeId: 2
attack:
  name: 'Stretta di Mano Apostolica'
  description: 'la Stretta di Mano Apostolica: ti tira su senza fare rumore: sembra una cosa da manuale, ma
    don Samuele la fa con stile. Critico su chi prende la vita troppo sul serio.'
  damage: 10
resistanceTypeId: 10
resistanceAmount: 10
weaknessTypeId: 3
weaknessModifier: times
weaknessAmount: 2
