id: 28
cardNumber: 28
dexStats: "NO. 0028"
name: 'Mega Samuele'
hitpoints: 70
typeId: 9
typeImageId: 9
subtypeId: 2
ability:
  name: 'Benedizione in Tasca'
  description: 'È la sua mossa segreta: ascolta davvero, senza fretta: sembra poco, ma è un superpotere
    rarissimo. Chi lo incontra capisce subito che la gioia può essere… liturgica.'
  energycost:
    a:
      typeId: 7
    b:
      typeId: 6
    c:
      typeId: 3
    d:
      typeId: 8
attack:
  name: 'Silenzio Sacro (poi risata)'
  description: 'don Samuele esegue un Incenso a Nebbia: atmosfera mistica, ma con vibe da festa patronale:
    colpo preciso, zero cattiveria, solo una valanga di ''Amen!'' e buonumore.'
  damage: 10
resistanceTypeId: 2
resistanceAmount: 30
weaknessTypeId: 7
weaknessModifier: plus
weaknessAmount: 10
