id: 28
cardNumber: 28
dexStats: "NO. 0028"
name: 'Mega Samuele'
hitpoints: 70
typeId: 9
typeImageId: 9
subtypeId: 2
ability:
  name: 'Disponibilità Totale'
  description: 'Se qualcuno chiede, lui c''è. Non per obbligo, ma per convinzione sincera.'
  energycost:
    a:
      typeId: 7
    b:
      typeId: 6
    c:
      typeId: 3
    d:
      typeId: 8
attack:
  name: 'Benedizione Mirata'
  description: 'Pronuncia poche parole, ma con intensità tale da lasciare un effetto immediato e duraturo.'
  damage: 10
resistanceTypeId: 2
resistanceAmount: 30
weaknessTypeId: 7
weaknessModifier: plus
weaknessAmount: 10
