id: 28
cardNumber: 28
dexStats: NO. 0028
name: Samucharizard
hitpoints: 70
typeId: 6
typeImageId: 6
subtypeId: 3
ability:
  name: 'Sacerdote Novello: Modalità Festa'
  description: Prima Messa? Sì, ma con gioia contagiosa. Tutti percepiscono che è un giorno speciale
    e ti scappa un sorriso.
  energycost:
    a:
      typeId: 2
    b:
      typeId: 1
    c:
      typeId: 5
    d:
      typeId: 4
attack:
  name: Rosario a Catena
  description: 'Un’Ave Maria tira l’altra: l’effetto è continuo e inarrestabile. Danno progressivo
    alla negatività.'
  damage: 7
resistanceTypeId: 4
resistanceModifier: times
resistanceAmount: 12
weaknessTypeId: 9
weaknessModifier: minus
weaknessAmount: 37
