id: 29
cardNumber: 29
dexStats: "NO. 0029"
name: 'Super Samu'
hitpoints: 150
typeId: 5
typeImageId: 5
subtypeId: 3
ability:
  name: 'Zero Ansia, Solo Grazia'
  description: 'Attiva questa abilità e succede il bello: ascolta davvero, senza fretta: sembra poco, ma è
    un superpotere rarissimo. Effetto collaterale: clima di famiglia garantito.'
  energycost:
    a:
      typeId: 9
    b:
      typeId: 1
    c:
      typeId: 6
    d:
      typeId: 10
attack:
  name: 'Scambio di Pace a Catena'
  description: 'Quando parte un ''Alleluia'' a volume 11: non è rumore, è gioia che trabocca, non c''''è difesa:
    ti ritrovi benedetto e con la faccia che ride.'
  damage: 50
resistanceTypeId: 3
resistanceAmount: 30
weaknessTypeId: 7
weaknessModifier: times
weaknessAmount: 2
