id: 29
cardNumber: 29
dexStats: "NO. 0029"
name: 'Super Samu'
hitpoints: 150
typeId: 5
typeImageId: 5
subtypeId: 3
ability:
  name: 'Serietà con Luce'
  description: 'Sa affrontare temi profondi senza appesantire. Il tono è serio, ma lo sguardo resta luminoso.'
  energycost:
    a:
      typeId: 9
    b:
      typeId: 1
    c:
      typeId: 6
    d:
      typeId: 10
attack:
  name: 'Prefazio in Crescendo'
  description: 'Inizia misurato e cresce con ritmo solenne. L''attenzione si concentra e il silenzio diventa pieno.'
  damage: 50
resistanceTypeId: 3
resistanceAmount: 30
weaknessTypeId: 7
weaknessModifier: times
weaknessAmount: 2
