id: 30
cardNumber: 30
dexStats: "NO. 0030"
name: 'Samuele'
hitpoints: 50
typeId: 3
typeImageId: 3
subtypeId: 1
ability:
  name: 'Luce da Presbiterio'
  description: 'don Samuele ha il talento raro di tira fuori la chitarra liturgica e mette tutti in modalità
    Alleluia. Risultato: anche la sacrestia sembra una pista da ballo (con rispetto).'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 6
    c:
      typeId: 4
    d:
      typeId: 9
attack:
  name: 'Sermone Laser'
  description: 'Con il Sacro & Spritz: brindisi sobrio, sorriso pieno, gratitudine ovunque, don Samuele
    spiazza tutti. L''''effetto è immediato: risate, pace e un leggero profumo d''''incenso.'
  damage: 30
resistanceTypeId: 4
resistanceAmount: 30
weaknessTypeId: 2
weaknessModifier: times
weaknessAmount: 2
