id: 30
cardNumber: 30
dexStats: "NO. 0030"
name: 'Samuele'
hitpoints: 50
typeId: 3
typeImageId: 3
subtypeId: 1
ability:
  name: 'Presenza che Rassicura'
  description: 'Basta averlo vicino per sentirsi più tranquilli. Non fa spettacolo, fa stabilità.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 6
    c:
      typeId: 4
    d:
      typeId: 9
attack:
  name: 'Amen Conclusivo'
  description: 'Pronunciato con decisione e pace, chiude ogni celebrazione con senso di completezza. Turno finito, serenità attiva.'  
  damage: 30
resistanceTypeId: 4
resistanceAmount: 30
weaknessTypeId: 2
weaknessModifier: times
weaknessAmount: 2
