id: 31
cardNumber: 31
dexStats: "NO. 0031"
name: 'Mega Samu'
hitpoints: 20
typeId: 10
typeImageId: 10
subtypeId: 1
ability:
  name: 'Accento da Lombardia'
  description: 'don Samuele ha il talento raro di fa ''calma olimpica'': anche se succede di tutto, lui resta
    centrato. Risultato: anche la sacrestia sembra una pista da ballo (con rispetto).'
  energycost:
    a:
      typeId: 9
    b:
      typeId: 10
    c:
      typeId: 3
    d:
      typeId: 2
attack:
  name: 'Campane in Dubstep'
  description: 'la Benedizione a Sorpresa: gesto fulmineo, cuore gigante, effetto ''Amen!'': sembra una cosa
    da manuale, ma don Samuele la fa con stile. Critico su chi prende la vita troppo sul serio.'
  damage: 50
resistanceTypeId: 9
resistanceAmount: 20
weaknessTypeId: 2
weaknessModifier: times
weaknessAmount: 2
