id: 31
cardNumber: 31
dexStats: "NO. 0031"
name: 'Mega Samu'
hitpoints: 20
typeId: 10
typeImageId: 10
subtypeId: 1
ability:
  name: 'Eccomi Mode Attivata'
  description: 'Quando qualcuno chiama, lui risponde come Samuele nella Scrittura: “Eccomi”. Solo che lo dice con un sorriso e magari con il telefono già in mano.'
  energycost:
    a:
      typeId: 9
    b:
      typeId: 10
    c:
      typeId: 3
    d:
      typeId: 2
attack:
  name: 'Chiamata Vocazionale Diretta'
  description: 'Uno sguardo, una frase, e ti senti coinvolto. Non obbliga nessuno, ma improvvisamente ti viene voglia di fare qualcosa di buono.'
  damage: 50
resistanceTypeId: 9
resistanceAmount: 20
weaknessTypeId: 2
weaknessModifier: times
weaknessAmount: 2
