id: 32
cardNumber: 32
dexStats: "NO. 0032"
name: 'Samu'
hitpoints: 110
typeId: 5
typeImageId: 5
subtypeId: 2
ability:
  name: 'Puntualit√† Miracolosa'
  description: 'don Samuele ha il talento raro di fa il rosario remix: ritmo semplice, intenzioni vere,
    niente pesantezza. Risultato: anche la sacrestia sembra una pista da ballo (con rispetto).'
  energycost:
    a:
      typeId: 9
    b:
      typeId: 7
    c:
      typeId: 4
    d:
      typeId: 3
attack:
  name: 'Benedizione ''No Look'''
  description: 'il Sacro & Spritz: brindisi sobrio, sorriso pieno, gratitudine ovunque: sembra una cosa da
    manuale, ma don Samuele la fa con stile. Critico su chi prende la vita troppo sul serio.'
  damage: 50
resistanceTypeId: 10
resistanceAmount: 30
weaknessTypeId: 2
weaknessModifier: plus
weaknessAmount: 20
