id: 32
cardNumber: 32
dexStats: "NO. 0032"
name: 'Samu'
hitpoints: 110
typeId: 5
typeImageId: 5
subtypeId: 2
ability:
  name: 'Moltiplicazione dei Sorrisi'
  description: 'Come pani e pesci, parte da uno e finisce per contagiare tutti. Più ne dona, più sembrano aumentare.'
  energycost:
    a:
      typeId: 9
    b:
      typeId: 7
    c:
      typeId: 4
    d:
      typeId: 3
attack:
  name: 'Parabola Illuminante'
  description: 'Racconta una storia semplice e all''improvviso tutto si chiarisce. Effetto: comprensione immediata e cenni di approvazione diffusi.'
  damage: 50
resistanceTypeId: 10
resistanceAmount: 30
weaknessTypeId: 2
weaknessModifier: plus
weaknessAmount: 20
