id: 33
cardNumber: 33
dexStats: "NO. 0033"
name: 'Samuele'
hitpoints: 30
typeId: 8
typeImageId: 8
subtypeId: 1
ability:
  name: 'Pastore con Sneakers'
  description: 'Guida con stile giovane ma cuore antico. Un piede sull''altare, l''altro nella vita vera.'
  energycost:
    a:
      typeId: 5
    b:
      typeId: 9
    c:
      typeId: 2
    d:
      typeId: 1
attack:
  name: 'Verbo Incarnato'
  description: 'Non solo parole: ci√≤ che dice lo vive. Colpo silenzioso ma potentissimo contro l''incoerenza.'
  damage: 40
resistanceTypeId: 9
resistanceAmount: 10
weaknessTypeId: 6
weaknessModifier: times
weaknessAmount: 2
