id: 34
cardNumber: 34
dexStats: "NO. 0034"
name: 'Super Samu'
hitpoints: 60
typeId: 9
typeImageId: 9
subtypeId: 1
ability:
  name: 'Luce sul Candelabro'
  description: 'Non cerca i riflettori, ma quando parla illumina. E la luce, si sa, non si mette sotto il moggio.'
  energycost:
    a:
      typeId: 2
    b:
      typeId: 8
    c:
      typeId: 5
    d:
      typeId: 10
attack:
  name: 'Alleluia Ascendente'
  description: 'Parte piano e sale come un salmo responsoriale ben riuscito. L''assemblea viene trascinata verso l''alto, quasi senza accorgersene.'
  damage: 20
resistanceTypeId: 9
resistanceAmount: 30
weaknessTypeId: 1
weaknessModifier: times
weaknessAmount: 2
