id: 34
cardNumber: 34
dexStats: "NO. 0034"
name: 'Super Samu'
hitpoints: 60
typeId: 9
typeImageId: 9
subtypeId: 1
ability:
  name: 'Risata Contagiosa'
  description: 'Quando don Samuele entra in scena, l''''atmosfera cambia: rassicura con uno sguardo:
    ''tranquillo, ci pensiamo insieme'' E sì, il sorriso diventa obbligatorio.'
  energycost:
    a:
      typeId: 2
    b:
      typeId: 8
    c:
      typeId: 5
    d:
      typeId: 10
attack:
  name: 'Pater Noster Turbo'
  description: 'don Samuele esegue il Silenzio Sacro… poi risata: tensione giù, fraternità su: colpo
    preciso, zero cattiveria, solo una valanga di ''Amen!'' e buonumore.'
  damage: 20
resistanceTypeId: 9
resistanceAmount: 30
weaknessTypeId: 1
weaknessModifier: times
weaknessAmount: 2
