id: 35
cardNumber: 35
dexStats: "NO. 0035"
name: 'Super Samuele'
hitpoints: 100
typeId: 5
typeImageId: 5
subtypeId: 2
ability:
  name: 'Cuore Grande (taglia XXL)'
  description: 'Quando don Samuele entra in scena, l''''atmosfera cambia: mescola Bibbia e playlist: la Parola
    resta… e anche il ritornello E sì, il sorriso diventa obbligatorio.'
  energycost:
    a:
      typeId: 6
    b:
      typeId: 7
    c:
      typeId: 5
    d:
      typeId: 10
attack:
  name: 'Cero Fiammeggiante'
  description: 'Quando parte un''''aspersione Splash che ti rinfresca l''''anima come una doccia d''''estate, non
    c''''è difesa: ti ritrovi benedetto e con la faccia che ride.'
  damage: 20
resistanceTypeId: 4
resistanceAmount: 20
weaknessTypeId: 8
weaknessModifier: plus
weaknessAmount: 30
