id: 35
cardNumber: 35
dexStats: "NO. 0035"
name: 'Super Samuele'
hitpoints: 100
typeId: 5
typeImageId: 5
subtypeId: 2
ability:
  name: 'Beatitudine Operativa'
  description: 'Beati quelli che hanno bisogno di incoraggiamento: lui arriva puntuale. Consolazione concreta, non teorica.'
  energycost:
    a:
      typeId: 6
    b:
      typeId: 7
    c:
      typeId: 5
    d:
      typeId: 10
attack:
  name: 'Amen a Effetto Domino'
  description: 'Pronuncia l''Amen con tale convinzione che rimbalza tra le navate. Fine della discussione, inizio della pace.'
  damage: 20
resistanceTypeId: 4
resistanceAmount: 20
weaknessTypeId: 8
weaknessModifier: plus
weaknessAmount: 30
