id: 36
cardNumber: 36
dexStats: "NO. 0036"
name: 'Mega Samu'
hitpoints: 40
typeId: 10
typeImageId: 10
subtypeId: 1
ability:
  name: 'Carisma Apostolico'
  description: 'Non cammina sulle acque, ma sulle relazioni s√¨. Sa costruire legami solidi senza fare miracoli scenografici.'
  energycost:
    a:
      typeId: 7
    b:
      typeId: 4
    c:
      typeId: 2
    d:
      typeId: 5
attack:
  name: 'Rete Gettata al Momento Giusto'
  description: 'Una parola ben scelta e raccoglie attenzione come pesci nella rete. Colpo evangelicamente efficace.'
  damage: 50
resistanceTypeId: 7
resistanceAmount: 20
weaknessTypeId: 4
weaknessModifier: times
weaknessAmount: 2
