id: 36
cardNumber: 36
dexStats: "NO. 0036"
name: 'Mega Samu'
hitpoints: 40
typeId: 10
typeImageId: 10
subtypeId: 1
ability:
  name: 'Bibbia & Playlist'
  description: 'Quando don Samuele entra in scena, l''''atmosfera cambia: porta una luce serena che fa
    sembrare tutto più possibile E sì, il sorriso diventa obbligatorio.'
  energycost:
    a:
      typeId: 7
    b:
      typeId: 4
    c:
      typeId: 2
    d:
      typeId: 5
attack:
  name: 'Colletta Improvvisata'
  description: 'Con la Benedizione a Sorpresa: gesto fulmineo, cuore gigante, effetto ''Amen!'', don Samuele
    spiazza tutti. L''''effetto è immediato: risate, pace e un leggero profumo d''''incenso.'
  damage: 50
resistanceTypeId: 7
resistanceAmount: 20
weaknessTypeId: 4
weaknessModifier: times
weaknessAmount: 2
