id: 37
cardNumber: 37
dexStats: "NO. 0037"
name: 'Mega Samu'
hitpoints: 50
typeId: 8
typeImageId: 8
subtypeId: 1
ability:
  name: 'Stile da Festa Patronale'
  description: 'Quando don Samuele entra in scena, l''''atmosfera cambia: accende la festa senza perdere il
    tono giusto, anche se spunta un prosecco E s√¨, il sorriso diventa obbligatorio.'
  energycost:
    a:
      typeId: 2
    b:
      typeId: 4
    c:
      typeId: 1
    d:
      typeId: 10
attack:
  name: 'Proclama & Boom'
  description: 'un Amen Mic Drop: chiusura netta, applauso interiore assicurato: sembra una cosa da manuale,
    ma don Samuele la fa con stile. Critico su chi prende la vita troppo sul serio.'
  damage: 30
resistanceTypeId: 10
resistanceAmount: 20
weaknessTypeId: 4
weaknessModifier: plus
weaknessAmount: 20
