id: 37
cardNumber: 37
dexStats: "NO. 0037"
name: 'Mega Samu'
hitpoints: 50
typeId: 8
typeImageId: 8
subtypeId: 1
ability:
  name: 'Incenso & Incanto'
  description: 'Sa rendere solenne ogni momento, ma con leggerezza. L''incenso sale e l''umore pure.'
  energycost:
    a:
      typeId: 2
    b:
      typeId: 4
    c:
      typeId: 1
    d:
      typeId: 10
attack:
  name: 'Turibolo Coreografico'
  description: 'Oscillazione perfetta, ritmo impeccabile. L''atmosfera si riempie di profumo e meraviglia.'
  damage: 30
resistanceTypeId: 10
resistanceAmount: 20
weaknessTypeId: 4
weaknessModifier: plus
weaknessAmount: 20
