id: 37
cardNumber: 37
dexStats: NO. 0037
name: Samucharizard
hitpoints: 20
typeId: 6
typeImageId: 6
subtypeId: 1
ability:
  name: Sguardo da “Ci Penso Io”
  description: 'Non promette a vuoto: guarda, valuta, risolve. Riduce un danno futuro perché ha
    già previsto la traiettoria.'
  energycost:
    a:
      typeId: 5
    b:
      typeId: 10
    c:
      typeId: 6
    d:
      typeId: 7
attack:
  name: Eucaristia di Energia
  description: Non è un power-up da videogame, eppure ti senti rinato. Colpo che fa bene e fa
    male (alle paure).
  damage: 26
resistanceTypeId: 1
resistanceModifier: plus
resistanceAmount: 16
weaknessTypeId: 9
weaknessModifier: times
weaknessAmount: 39
