id: 38
cardNumber: 38
dexStats: "NO. 0038"
name: 'Super Samuele'
hitpoints: 50
typeId: 9
typeImageId: 9
subtypeId: 1
ability:
  name: 'Cuore in Offertorio'
  description: 'Non offre solo pane e vino: mette dentro ogni celebrazione un pezzo di s√©. E questo si sente.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 9
    c:
      typeId: 6
    d:
      typeId: 7
attack:
  name: 'Prefazio da Brividi'
  description: 'Intona con voce sicura e l''attenzione si fa totale. Anche chi era distratto si riallinea.'
  damage: 40
resistanceTypeId: 9
resistanceAmount: 20
weaknessTypeId: 1
weaknessModifier: times
weaknessAmount: 2
