id: 39
cardNumber: 39
dexStats: "NO. 0039"
name: 'Samuele'
hitpoints: 40
typeId: 3
typeImageId: 3
subtypeId: 1
ability:
  name: 'Pace che Supera Ogni Difesa'
  description: 'La sua pace non è formale: è concreta, calda, reale. Ti arriva addosso e ti disarma con eleganza.'
  energycost:
    a:
      typeId: 10
    b:
      typeId: 3
    c:
      typeId: 8
    d:
      typeId: 5
attack:
  name: 'Segno della Croce Definitivo'
  description: 'Tracciato con calma e convinzione, sembra semplice. Ma lascia un impatto che dura ben oltre il gesto.'
  damage: 40
resistanceTypeId: 3
resistanceAmount: 30
weaknessTypeId: 8
weaknessModifier: plus
weaknessAmount: 30
