id: 39
cardNumber: 39
dexStats: "NO. 0039"
name: 'Samuele'
hitpoints: 40
typeId: 3
typeImageId: 3
subtypeId: 1
ability:
  name: 'Ascolto Attivo'
  description: 'don Samuele ha il talento raro di accende l''''allegria anche con una benedizione in tasca,
    pronta all''''uso. Risultato: anche la sacrestia sembra una pista da ballo (con rispetto).'
  energycost:
    a:
      typeId: 10
    b:
      typeId: 3
    c:
      typeId: 8
    d:
      typeId: 5
attack:
  name: 'Festa Patronale Finale'
  description: 'Con una Pace Scambiata Rapidissima: catena di sorrisi e mani, nessuno scappa, don Samuele
    spiazza tutti. L''''effetto Ã¨ immediato: risate, pace e un leggero profumo d''''incenso.'
  damage: 40
resistanceTypeId: 3
resistanceAmount: 30
weaknessTypeId: 8
weaknessModifier: plus
weaknessAmount: 30
