id: 40
cardNumber: 40
dexStats: "NO. 0040"
name: 'Mega Samu'
hitpoints: 60
typeId: 3
typeImageId: 3
subtypeId: 2
ability:
  name: 'Calma Olimpica'
  description: 'don Samuele ha il talento raro di fa catechesi pop: esempi quotidiani, cuore grande e zero
    predicozzi. Risultato: anche la sacrestia sembra una pista da ballo (con rispetto).'
  energycost:
    a:
      typeId: 6
    b:
      typeId: 9
    c:
      typeId: 7
    d:
      typeId: 2
attack:
  name: 'Rosario a Tempo'
  description: 'un''''aspersione Splash che ti rinfresca l''''anima come una doccia d''''estate: sembra una cosa
    da manuale, ma don Samuele la fa con stile. Critico su chi prende la vita troppo sul serio.'
  damage: 10
resistanceTypeId: 4
resistanceAmount: 20
weaknessTypeId: 8
weaknessModifier: times
weaknessAmount: 2
