id: 40
cardNumber: 40
dexStats: "NO. 0040"
name: 'Mega Samu'
hitpoints: 60
typeId: 3
typeImageId: 3
subtypeId: 2
ability:
  name: 'Gioia da Risurrezione'
  description: 'Anche nei momenti seri, trova sempre una luce. Non banalizza, ma ricorda che la speranza è l''ultima parola.'
  energycost:
    a:
      typeId: 6
    b:
      typeId: 9
    c:
      typeId: 7
    d:
      typeId: 2
attack:
  name: 'Uscita in Gloria'
  description: 'Conclude, saluta, benedice. E mentre esce, lascia dietro di sé una scia di serenità che vale più di mille effetti speciali.'  
  damage: 10
resistanceTypeId: 4
resistanceAmount: 20
weaknessTypeId: 8
weaknessModifier: times
weaknessAmount: 2
