id: 41
cardNumber: 41
dexStats: "NO. 0041"
name: 'Super Samu'
hitpoints: 120
typeId: 3
typeImageId: 3
subtypeId: 3
ability:
  name: 'Resta Qui con Noi Mode'
  description: 'Quando intona “Resta qui con noi”, non è solo il ritornello: è un invito vero. E alla fine restano tutti, anche quelli che avevano già preso le chiavi.'
  energycost:
    a:
      typeId: 3
    b:
      typeId: 7
    c:
      typeId: 9
    d:
      typeId: 2
attack:
  name: 'Luce che Non Tramonta'
  description: 'Parte piano, quasi sottovoce, poi cresce come il canto finale di un campo estivo. Risultato: atmosfera accesa e cuori leggermente sciolti.'
  damage: 20
resistanceTypeId: 9
resistanceAmount: 10
weaknessTypeId: 8
weaknessModifier: times
weaknessAmount: 2
