id: 41
cardNumber: 41
dexStats: "NO. 0041"
name: 'Super Samu'
hitpoints: 120
typeId: 3
typeImageId: 3
subtypeId: 3
ability:
  name: 'Fede Wi‑Fi'
  description: 'don Samuele ha il talento raro di tiene il gruppo unito: nessuno resta indietro, nessuno
    resta solo. Risultato: anche la sacrestia sembra una pista da ballo (con rispetto).'
  energycost:
    a:
      typeId: 3
    b:
      typeId: 7
    c:
      typeId: 9
    d:
      typeId: 2
attack:
  name: 'Coro Stadio (ma santo)'
  description: 'Quando parte la Genuflessione Ninja: silenziosa, precisa, e ti fa venir voglia di fare
    meglio, non c''''è difesa: ti ritrovi benedetto e con la faccia che ride.'
  damage: 20
resistanceTypeId: 9
resistanceAmount: 10
weaknessTypeId: 8
weaknessModifier: times
weaknessAmount: 2
