id: 41
cardNumber: 41
dexStats: NO. 0041
name: Samu
hitpoints: 20
typeId: 5
typeImageId: 5
subtypeId: 1
ability:
  name: La “S” di Samu sulla Stola
  description: 'Non si vede, ma si sente: quando indossa la stola, diventa super. Aumenti la tua
    protezione per un turno.'
  energycost:
    a:
      typeId: 1
    b:
      typeId: 3
    c:
      typeId: 8
    d:
      typeId: 5
attack:
  name: Inchino da Cerimoniale
  description: 'Un inchino fatto bene è già metà della vittoria: eleganza letale. Danno tecnico.'
  damage: 34
resistanceTypeId: 3
resistanceModifier: times
resistanceAmount: 38
weaknessTypeId: 7
weaknessModifier: times
weaknessAmount: 5
