id: 42
cardNumber: 42
dexStats: "NO. 0042"
name: 'Super Samuele'
hitpoints: 40
typeId: 10
typeImageId: 10
subtypeId: 1
ability:
  name: 'Servo per Amore (ma con stile)'
  description: '“Una notte di sudore…” lui la conosce bene, ma riesce a servirti con eleganza e una battuta pronta. Umiltà sì, ma con personalità.'
  energycost:
    a:
      typeId: 9
    b:
      typeId: 8
    c:
      typeId: 4
    d:
      typeId: 2
attack:
  name: 'Grido del Popolo in Festa'
  description: 'Quando l''assemblea si scalda, lui guida il coro con entusiasmo contagioso. Nessuno resta seduto, nemmeno il più timido.'
  damage: 30
resistanceTypeId: 5
resistanceAmount: 20
weaknessTypeId: 1
weaknessModifier: plus
weaknessAmount: 20
