id: 42
cardNumber: 42
dexStats: "NO. 0042"
name: 'Super Samuele'
hitpoints: 40
typeId: 10
typeImageId: 10
subtypeId: 1
ability:
  name: 'Catechesi Pop'
  description: 'Quando don Samuele entra in scena, l''''atmosfera cambia: tiene il gruppo unito: nessuno resta
    indietro, nessuno resta solo E sì, il sorriso diventa obbligatorio.'
  energycost:
    a:
      typeId: 9
    b:
      typeId: 8
    c:
      typeId: 4
    d:
      typeId: 2
attack:
  name: 'Incenso a Spray'
  description: 'Quando parte una Predica Beat: due concetti chiari e un ritmo che resta in testa, non c''''è
    difesa: ti ritrovi benedetto e con la faccia che ride.'
  damage: 30
resistanceTypeId: 5
resistanceAmount: 20
weaknessTypeId: 1
weaknessModifier: plus
weaknessAmount: 20
