id: 43
cardNumber: 43
dexStats: "NO. 0043"
name: 'Super Samu'
hitpoints: 70
typeId: 9
typeImageId: 9
subtypeId: 2
ability:
  name: 'Come Fuoco Vivo'
  description: 'Non urla, non impone: scalda. E quando parte il ritornello, il suo entusiasmo sembra un falò ben controllato.'
  energycost:
    a:
      typeId: 7
    b:
      typeId: 8
    c:
      typeId: 9
    d:
      typeId: 4
attack:
  name: 'Alza le Braccia (Consapevolmente)'
  description: 'Invita tutti ad alzare le mani… ma con dignità liturgica. Effetto: partecipazione massima e sorrisi sincronizzati.'
  damage: 20
resistanceTypeId: 5
resistanceAmount: 30
weaknessTypeId: 3
weaknessModifier: plus
weaknessAmount: 10
