id: 43
cardNumber: 43
dexStats: "NO. 0043"
name: 'Super Samu'
hitpoints: 70
typeId: 9
typeImageId: 9
subtypeId: 2
ability:
  name: 'Pace Distribuita'
  description: 'Quando don Samuele entra in scena, l''''atmosfera cambia: fa omelie brevi ma memorabili: una
    frase, un sorriso, e ti resta addosso per ore E s√¨, il sorriso diventa obbligatorio.'
  energycost:
    a:
      typeId: 7
    b:
      typeId: 8
    c:
      typeId: 9
    d:
      typeId: 4
attack:
  name: 'Altare Drift'
  description: 'don Samuele esegue un Amen Mic Drop: chiusura netta, applauso interiore assicurato: colpo
    preciso, zero cattiveria, solo una valanga di ''Amen!'' e buonumore.'
  damage: 20
resistanceTypeId: 5
resistanceAmount: 30
weaknessTypeId: 3
weaknessModifier: plus
weaknessAmount: 10
