id: 44
cardNumber: 44
dexStats: "NO. 0044"
name: 'Samu'
hitpoints: 60
typeId: 10
typeImageId: 10
subtypeId: 1
ability:
  name: 'Esci dalla Tua Terra (ma Torna per la Cena)'
  description: 'Sprona a mettersi in cammino, a osare, a fidarsi. Però ricorda sempre che la comunità ti aspetta a tavola.'
  energycost:
    a:
      typeId: 10
    b:
      typeId: 7
    c:
      typeId: 3
    d:
      typeId: 8
attack:
  name: 'Camminerò con Te'
  description: 'Non corre avanti, non trascina: cammina accanto. Colpo lento ma efficace contro la solitudine.'
  damage: 40
resistanceTypeId: 3
resistanceAmount: 30
weaknessTypeId: 6
weaknessModifier: plus
weaknessAmount: 20
