id: 44
cardNumber: 44
dexStats: "NO. 0044"
name: 'Samu'
hitpoints: 60
typeId: 10
typeImageId: 10
subtypeId: 1
ability:
  name: 'Sguardo che Rassicura'
  description: 'È la sua mossa segreta: usa l''''ironia con delicatezza: fa ridere senza ferire, mai. Chi lo
    incontra capisce subito che la gioia può essere… liturgica.'
  energycost:
    a:
      typeId: 10
    b:
      typeId: 7
    c:
      typeId: 3
    d:
      typeId: 8
attack:
  name: 'Pace, Bro!'
  description: 'le Campane in Dubstep: vibrazione pura, nessuno resta fermo: sembra una cosa da manuale, ma
    don Samuele la fa con stile. Critico su chi prende la vita troppo sul serio.'
  damage: 40
resistanceTypeId: 3
resistanceAmount: 30
weaknessTypeId: 6
weaknessModifier: plus
weaknessAmount: 20
