id: 45
cardNumber: 45
dexStats: "NO. 0045"
name: 'Super Samu'
hitpoints: 20
typeId: 7
typeImageId: 7
subtypeId: 1
ability:
  name: 'Andate per le Strade… e Fate Rumore'
  description: 'Prende il mandato sul serio: invita a uscire, testimoniare e vivere con gioia. Con moderazione, ma senza silenzi imbarazzanti.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 6
    c:
      typeId: 10
    d:
      typeId: 4
attack:
  name: 'Alleluia in Loop'
  description: 'Ripete il ritornello finché anche chi non canta si ritrova a canticchiare. Strategia semplice, risultato inevitabile.'  
  damage: 10
resistanceTypeId: 7
resistanceAmount: 20
weaknessTypeId: 5
weaknessModifier: times
weaknessAmount: 2
