id: 45
cardNumber: 45
dexStats: NO. 0045
name: Samucharizard
hitpoints: 110
typeId: 1
typeImageId: 1
subtypeId: 3
ability:
  name: Sermone Anti-Drama
  description: Taglia il drama con una frase gentile e una risata. Neutralizza un conflitto nascente.
  energycost:
    a:
      typeId: 4
    b:
      typeId: 2
    c:
      typeId: 5
    d:
      typeId: 6
attack:
  name: Benedizione “A Area”
  description: 'Come un portiere che copre tutta la porta: benedice e protegge tutti. Danno e
    protezione.'
  damage: 25
resistanceTypeId: 1
resistanceModifier: minus
resistanceAmount: 18
weaknessTypeId: 4
weaknessModifier: times
weaknessAmount: 18
