id: 45
cardNumber: 45
dexStats: "NO. 0045"
name: 'Super Samu'
hitpoints: 20
typeId: 7
typeImageId: 7
subtypeId: 1
ability:
  name: 'Fazzoletti Sempre Pronti'
  description: 'Quando don Samuele entra in scena, l''''atmosfera cambia: canta litanie e inni come un tenore…
    soprattutto quando parte quello dell''''Inter E sì, il sorriso diventa obbligatorio.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 6
    c:
      typeId: 10
    d:
      typeId: 4
attack:
  name: 'Liturgia Speedrun'
  description: 'Quando parte il Sacro & Spritz: brindisi sobrio, sorriso pieno, gratitudine ovunque, non
    c''''è difesa: ti ritrovi benedetto e con la faccia che ride.'
  damage: 10
resistanceTypeId: 7
resistanceAmount: 20
weaknessTypeId: 5
weaknessModifier: times
weaknessAmount: 2
