id: 46
cardNumber: 46
dexStats: "NO. 0046"
name: 'Super Samuele'
hitpoints: 160
typeId: 9
typeImageId: 9
subtypeId: 3
ability:
  name: 'Fede Nerazzurra Incrollabile'
  description: 'La sua fede è solida. In chiesa è teologale, allo stadio è nerazzurra. Soffre, spera, esulta… ma sempre con compostezza (quasi sempre).'
  energycost:
    a:
      typeId: 5
    b:
      typeId: 8
    c:
      typeId: 6
    d:
      typeId: 3
attack:
  name: 'Derby Benedetto'
  description: 'Quando gioca l’Inter, l’intensità sale. Se segna, il suo “Amen” ha un tono leggermente più trionfale. Coincidenze? Forse.'
  damage: 40
resistanceTypeId: 6
resistanceAmount: 30
weaknessTypeId: 4
weaknessModifier: times
weaknessAmount: 2
