id: 47
cardNumber: 47
dexStats: "NO. 0047"
name: 'Mega Samu'
hitpoints: 90
typeId: 9
typeImageId: 9
subtypeId: 2
ability:
  name: 'Ricarica Spirituale'
  description: 'È la sua mossa segreta: accende la festa senza perdere il tono giusto, anche se spunta un
    prosecco. Chi lo incontra capisce subito che la gioia può essere… liturgica.'
  energycost:
    a:
      typeId: 7
    b:
      typeId: 10
    c:
      typeId: 8
    d:
      typeId: 3
attack:
  name: 'Sacro & Spritz'
  description: 'il Rosario a Tempo: un passo, un''Ave, e via con il cuore leggero: sembra una cosa da
    manuale, ma don Samuele la fa con stile. Critico su chi prende la vita troppo sul serio.'
  damage: 30
resistanceTypeId: 2
resistanceAmount: 30
weaknessTypeId: 8
weaknessModifier: plus
weaknessAmount: 30
