id: 47
cardNumber: 47
dexStats: "NO. 0047"
name: 'Mega Samu'
hitpoints: 90
typeId: 9
typeImageId: 9
subtypeId: 2
ability:
  name: 'Coro da Curva (Versione Liturgica)'
  description: 'Ha imparato che il ritmo è tutto: dal “Forza Inter” al salmo responsoriale il passo è breve. Guida il canto con la stessa convinzione.'
  energycost:
    a:
      typeId: 7
    b:
      typeId: 10
    c:
      typeId: 8
    d:
      typeId: 3
attack:
  name: 'Triplice Fischio Finale'
  description: 'Sa attendere con pazienza fino all’ultimo minuto. Poi, quando arriva il momento giusto, chiude la partita… o la celebrazione… con precisione impeccabile.'  
  damage: 30
resistanceTypeId: 2
resistanceAmount: 30
weaknessTypeId: 8
weaknessModifier: plus
weaknessAmount: 30
