id: 48
cardNumber: 48
dexStats: "NO. 0048"
name: 'Samuele'
hitpoints: 40
typeId: 7
typeImageId: 7
subtypeId: 1
ability:
  name: 'Regola del ''Mai Solo'''
  description: 'È la sua mossa segreta: distribuisce ''pace'' a catena: in tre minuti si sciolgono anche i
    musi lunghi. Chi lo incontra capisce subito che la gioia può essere… liturgica.'
  energycost:
    a:
      typeId: 4
    b:
      typeId: 5
    c:
      typeId: 10
    d:
      typeId: 8
attack:
  name: 'Omnia Vincit Sorriso'
  description: 'Con la Grazia che Spiazza: ti sorprende proprio quando pensavi di non farcela, don Samuele
    spiazza tutti. L''''effetto è immediato: risate, pace e un leggero profumo d''''incenso.'
  damage: 10
resistanceTypeId: 3
resistanceAmount: 20
weaknessTypeId: 7
weaknessModifier: plus
weaknessAmount: 10
