id: 48
cardNumber: 48
dexStats: "NO. 0048"
name: 'Samuele'
hitpoints: 40
typeId: 7
typeImageId: 7
subtypeId: 1
ability:
  name: 'Modalità Oratorio ON'
  description: 'Appena sente la parola ORATORIO, si attiva automaticamente: sorriso largo, cappellino in testa e megafono pronto. L’energia non finisce mai (quasi).'
  energycost:
    a:
      typeId: 4
    b:
      typeId: 5
    c:
      typeId: 10
    d:
      typeId: 8
attack:
  name: 'Gavettone Benedetto'
  description: 'Quando parte la battaglia d’acqua, non si tira indietro. Colpisce con precisione pastorale e rinfresca anche le anime più accaldate.'
  damage: 10
resistanceTypeId: 3
resistanceAmount: 20
weaknessTypeId: 7
weaknessModifier: plus
weaknessAmount: 10
