id: 49
cardNumber: 49
dexStats: "NO. 0049"
name: 'Super Samuele'
hitpoints: 70
typeId: 8
typeImageId: 8
subtypeId: 2
ability:
  name: 'Resistenza da Campo Estivo'
  description: 'Dorme poco, parla tanto, cammina ovunque e non perde il buonumore. La sera è stanco, ma il cuore è ancora in modalità “gioia piena”.'
  energycost:
    a:
      typeId: 5
    b:
      typeId: 6
    c:
      typeId: 1
    d:
      typeId: 10
attack:
  name: 'Animazione a Raffica'
  description: 'Bans, urla di gioia e coreografie improvvisate: trascina tutti dentro il gioco. Anche chi aveva detto “io non partecipo”.'
  damage: 30
resistanceTypeId: 7
resistanceAmount: 10
weaknessTypeId: 10
weaknessModifier: times
weaknessAmount: 2
