id: 49
cardNumber: 49
dexStats: "NO. 0049"
name: 'Super Samuele'
hitpoints: 70
typeId: 8
typeImageId: 8
subtypeId: 2
ability:
  name: 'Spirito di Squadra'
  description: 'don Samuele ha il talento raro di fa ''calma olimpica'': anche se succede di tutto, lui resta
    centrato. Risultato: anche la sacrestia sembra una pista da ballo (con rispetto).'
  energycost:
    a:
      typeId: 5
    b:
      typeId: 6
    c:
      typeId: 1
    d:
      typeId: 10
attack:
  name: 'Alleluia Clap'
  description: 'don Samuele esegue le Campane in Dubstep: vibrazione pura, nessuno resta fermo: colpo
    preciso, zero cattiveria, solo una valanga di ''Amen!'' e buonumore.'
  damage: 30
resistanceTypeId: 7
resistanceAmount: 10
weaknessTypeId: 10
weaknessModifier: times
weaknessAmount: 2
