id: 49
cardNumber: 49
dexStats: NO. 0049
name: SuperSamu
hitpoints: 20
typeId: 3
typeImageId: 3
subtypeId: 1
ability:
  name: Sorriso da Foto di Gruppo
  description: La foto viene sempre bene perché lui riesce a far ridere proprio tutti. Bonus carisma
    per un turno.
  energycost:
    a:
      typeId: 9
    b:
      typeId: 1
    c:
      typeId: 4
    d:
      typeId: 6
attack:
  name: 'Amen: Colpo di Grazia'
  description: Non nel senso ‘fine del mondo’, ma ‘fine del problema’. Con un Amen, la questione
    si risolve. Danno decisivo.
  damage: 44
resistanceTypeId: 8
resistanceModifier: minus
resistanceAmount: 13
weaknessTypeId: 2
weaknessModifier: plus
weaknessAmount: 24
