id: 50
cardNumber: 50
dexStats: "NO. 0050"
name: 'Mega Samu'
hitpoints: 20
typeId: 9
typeImageId: 9
subtypeId: 1
ability:
  name: 'Fischietto dell’Autorità Dolce'
  description: 'Un solo fischio e cento ragazzi si voltano. Non per paura, ma perché sanno che sta per iniziare qualcosa di bello.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 2
    c:
      typeId: 9
    d:
      typeId: 7
attack:
  name: 'Caccia al Tesoro Spirituale'
  description: 'Organizza prove impossibili che finiscono sempre con una scoperta semplice: il vero premio è stare insieme. Ma il gelato aiuta.'
  damage: 50
resistanceTypeId: 7
resistanceAmount: 10
weaknessTypeId: 10
weaknessModifier: times
weaknessAmount: 2
