id: 50
cardNumber: 50
dexStats: "NO. 0050"
name: 'Mega Samu'
hitpoints: 20
typeId: 9
typeImageId: 9
subtypeId: 1
ability:
  name: 'Tono Giusto'
  description: 'Attiva questa abilità e succede il bello: firma con sorriso ogni incontro: la gente se ne va
    più leggera. Effetto collaterale: clima di famiglia garantito.'
  energycost:
    a:
      typeId: 8
    b:
      typeId: 2
    c:
      typeId: 9
    d:
      typeId: 7
attack:
  name: 'Amen Mic Drop'
  description: 'Con la Processione Parkour: ordinata ma energica, come una sfilata di gioia, don Samuele
    spiazza tutti. L''''effetto è immediato: risate, pace e un leggero profumo d''''incenso.'
  damage: 50
resistanceTypeId: 7
resistanceAmount: 10
weaknessTypeId: 10
weaknessModifier: times
weaknessAmount: 2
