id: 51
cardNumber: 51
dexStats: "NO. 0051"
name: 'Mega Samu'
hitpoints: 120
typeId: 2
typeImageId: 2
subtypeId: 2
ability:
  name: 'Catechesi in Versione Power-Up'
  description: 'Sa spiegare cose profondissime con esempi di palloni sgonfi, creme solari e partite infinite. Tutti capiscono. E qualcuno prende appunti.'
  energycost:
    a:
      typeId: 10
    b:
      typeId: 7
    c:
      typeId: 4
    d:
      typeId: 6
attack:
  name: 'Serata Sotto le Stelle'
  description: 'Quando cala il silenzio del campo estivo, tira fuori parole che scaldano più del falò. Effetto: occhi lucidi e cuori leggeri.'
  damage: 40
resistanceTypeId: 3
resistanceAmount: 30
weaknessTypeId: 8
weaknessModifier: times
weaknessAmount: 2
