id: 51
cardNumber: 51
dexStats: "NO. 0051"
name: 'Mega Samu'
hitpoints: 120
typeId: 2
typeImageId: 2
subtypeId: 2
ability:
  name: 'Samu in Modalità Festa'
  description: 'È la sua mossa segreta: tiene il gruppo unito: nessuno resta indietro, nessuno resta solo.
    Chi lo incontra capisce subito che la gioia può essere… liturgica.'
  energycost:
    a:
      typeId: 10
    b:
      typeId: 7
    c:
      typeId: 4
    d:
      typeId: 6
attack:
  name: 'Processione Parkour'
  description: 'don Samuele esegue la Benedizione a Sorpresa: gesto fulmineo, cuore gigante, effetto
    ''Amen!'': colpo preciso, zero cattiveria, solo una valanga di ''Amen!'' e buonumore.'
  damage: 40
resistanceTypeId: 3
resistanceAmount: 30
weaknessTypeId: 8
weaknessModifier: times
weaknessAmount: 2
