id: 52
cardNumber: 52
dexStats: "NO. 0052"
name: 'Mega Samu'
hitpoints: 20
typeId: 9
typeImageId: 9
subtypeId: 1
ability:
  name: 'Complicità da Cortile'
  description: 'Non è solo guida: è compagno di squadra. Sa quando ridere, quando ascoltare e quando lasciare che siano i ragazzi a brillare.'
  energycost:
    a:
      typeId: 7
    b:
      typeId: 3
    c:
      typeId: 1
    d:
      typeId: 10
attack:
  name: 'Finale con Ballo di Gruppo'
  description: 'L’ultimo giorno parte la musica, e lui è in prima fila. Coordina passi improbabili con entusiasmo contagioso. Standing ovation garantita.'  
  damage: 40
resistanceTypeId: 5
resistanceAmount: 30
weaknessTypeId: 1
weaknessModifier: times
weaknessAmount: 2
